package com.anynet.wifiworld.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.anynet.wifiworld.dao.SysMessage;

import com.anynet.wifiworld.dao.SysMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sysMessageDaoConfig;

    private final SysMessageDao sysMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sysMessageDaoConfig = daoConfigMap.get(SysMessageDao.class).clone();
        sysMessageDaoConfig.initIdentityScope(type);

        sysMessageDao = new SysMessageDao(sysMessageDaoConfig, this);

        registerDao(SysMessage.class, sysMessageDao);
    }
    
    public void clear() {
        sysMessageDaoConfig.getIdentityScope().clear();
    }

    public SysMessageDao getSysMessageDao() {
        return sysMessageDao;
    }

}
