package com.anynet.wifiworld.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYS_MESSAGE.
 */
public class SysMessage {

    private Long id;
    private Long serverId;
    private String content;
    private String title;
    private Integer type;
    private Long date;
    private Integer state; //1 未读  2已读,  -1 已经被删除

    public SysMessage() {
    }

    public SysMessage(Long id) {
        this.id = id;
    }

    public SysMessage(Long id, Long serverId, String content, String title, Integer type, Long date, Integer state) {
        this.id = id;
        this.serverId = serverId;
        this.content = content;
        this.title = title;
        this.type = type;
        this.date = date;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServerId() {
        return serverId;
    }

    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

}
